---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: amd64/eclipse-temurin:11-jdk-jammy
    environment:
      GRADLE_USER_HOME: ~/.gradle
    command: [ /bin/bash ]
    commands:
      - ./gradlew test
      - ./gradlew prepare
      - echo -n "1.0.$DRONE_BUILD_NUMBER,latest" > .tags
      - echo -n "1.0.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
    when:
      branch: master
      event: push

  - name: deploy_and_restart
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: digitalocean_host
      username:
        from_secret: digitalocean_user
      key:
        from_secret: digitalocean_key
      script:
        - service luxmed-bot stop
        - (cd ~/luxmed-bot && rm -f docker-compose.yml && wget https://raw.githubusercontent.com/dyrkin/luxmed-booking-service/master/docker/docker-compose.yml)
        - service luxmed-bot start
    when:
      branch: master
      event: push


---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: arm64v8/eclipse-temurin:11-jdk-jammy
    environment:
      GRADLE_USER_HOME: ~/.gradle
    command: [ /bin/bash ]
    commands:
      - ./gradlew prepare
      - echo -n "1.0.$DRONE_BUILD_NUMBER-arm64,latest-arm64" > .tags
      - echo -n "1.0.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile.arm64
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile.arm64
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile.arm64
      context: docker/
    when:
      branch: master
      event: push
