version = 3.8.3
runner.dialect = scala3
preset = IntelliJ
maxColumn = 120
project.git = true

align.preset = some
docstrings.style = SpaceAsterisk
docstrings.oneline = fold
docstrings.wrap = no
docstrings.blankFirstLine = yes