version: '3.4'
services:
  database:
    image: postgres:10.6
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=lbs
    - POSTGRES_PASSWORD=lsb123
    - POSTGRES_DB=lbs
    - TZ=Europe/Warsaw
